# Generated by Django 6.0.3 on 2026-05-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_milestone_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
